### PR TITLE
Added a --version option for displaying version info

### PR DESCRIPTION
**Pull request by paninaro**

### CODE REVIEW

**Comment by paninaro** [comment]
Should I append "-chia" to the version string? Or just leave it as the date string?

**Review by fchirica — APPROVED** [review]
I would vote for `2021.08.25-alpha`

**Comment by harold-b** [comment]
I'd argue that keeping the `-chia` makes sense for the user to distinguish that this is a chia-maintained fork, and not official versioning.

**Review by harold-b — APPROVED** [review]

**Comment by altendky** [comment]
I would think that `chia` would be a separate tag from `alpha`.  Having both would certainly be good sometimes.  But yes, as long as we are making our own adjusted builds we should mark them.  I suspect there's some level of standard for this but I don't know where offhand.

**Pull request merged**
